#!/bin/bash -xe
umask 002
date
sudo lb clean
sudo lb config
sudo lb build
mv binary.hybrid.iso binary27.hybrid.iso
mv binary.hybrid.iso.zsync binary27.hybrid.iso.zsync
#scp *.zsync *.iso timeguy.com:timeguy
#ssh -t emcboard@www.linuxcnc.org 'cd www.linuxcnc.org; ~/zsync-0.6.2/zsync http://timeguy.com/binary.hybrid.iso.zsync; rm binary.hybrid.iso.zsync; wget http://timeguy.com/binary.hybrid.iso.zsync; chmod 644 binary*'
date
