#!/bin/bash -xe
umask 002
date
sudo lb clean 
sudo lb config 	--apt-options "--yes --force-yes -o Acquire::Check-Valid-Until=false" \
				--updates false \
				--security true\
				--parent-mirror-bootstrap http://archive.debian.org/debian \
				--parent-mirror-chroot-security http://archive.debian.org/debian-security \
				--parent-mirror-binary-security http://archive.debian.org/debian-security \
				--parent-mirror-debian-installer http://archive.debian.org/debian \
				--parent-mirror-binary http://archive.debian.org/debian \
				--mirror-bootstrap http://archive.debian.org/debian
sudo lb build --verbose
mv binary.hybrid.iso binary27.hybrid.iso
mv binary.hybrid.iso.zsync binary27.hybrid.iso.zsync
#scp *.zsync *.iso timeguy.com:timeguy
#ssh -t emcboard@www.linuxcnc.org 'cd www.linuxcnc.org; ~/zsync-0.6.2/zsync http://timeguy.com/binary.hybrid.iso.zsync; rm binary.hybrid.iso.zsync; wget http://timeguy.com/binary.hybrid.iso.zsync; chmod 644 binary*'
date
